/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.23
 * Generated at: 2024-05-15 17:18:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Bus Route Selection</title>\r\n");
      out.write("    <style>\r\n");
      out.write("		body {\r\n");
      out.write("		    font-family: Arial, sans-serif;\r\n");
      out.write("		    margin: 0;\r\n");
      out.write("		    padding: 0;\r\n");
      out.write("		    background-color: #f4f4f4;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.container {\r\n");
      out.write("		    max-width: 600px;\r\n");
      out.write("		    margin: 50px auto;\r\n");
      out.write("		    padding: 20px;\r\n");
      out.write("		    background-color: #fff;\r\n");
      out.write("		    border-radius: 5px;\r\n");
      out.write("		    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		h1 {\r\n");
      out.write("		    text-align: center;\r\n");
      out.write("		    color: #333;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		label {\r\n");
      out.write("		    display: block;\r\n");
      out.write("		    margin-bottom: 10px;\r\n");
      out.write("		    color: #555;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		select {\r\n");
      out.write("		    width: 100%;\r\n");
      out.write("		    padding: 10px;\r\n");
      out.write("		    font-size: 16px;\r\n");
      out.write("		    border: 1px solid #ccc;\r\n");
      out.write("		    border-radius: 5px;\r\n");
      out.write("		    outline: none;\r\n");
      out.write("		    box-sizing: border-box;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		select:focus {\r\n");
      out.write("		    border-color: #007bff;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		select option:hover {\r\n");
      out.write("		    background-color: #007bff;\r\n");
      out.write("		    color: #fff;\r\n");
      out.write("		}\r\n");
      out.write("        .payment-btn {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            background-color: #007bff;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-btn:hover {\r\n");
      out.write("            background-color: #0056b3;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            background-color: #f0f0f0;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .route {\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            margin: 20px auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .route h1 {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .route p {\r\n");
      out.write("            color: #666;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .route p:first-child {\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .footer {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .footer img {\r\n");
      out.write("            margin: 0 10px;\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            animation: bounce 1s infinite alternate;\r\n");
      out.write("        }\r\n");
      out.write("        @keyframes bounce {\r\n");
      out.write("            0% {\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("            100% {\r\n");
      out.write("                transform: translateY(-10px);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        .header-bar {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px 0;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .header-bar a {\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            margin: 0 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .header-bar a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header-bar\">\r\n");
      out.write("    <a href=\"#\">Login</a>\r\n");
      out.write("    <a href=\"#\">Terms and Conditions</a>\r\n");
      out.write("    <a href=\"#\">FAQ</a>\r\n");
      out.write("    <a href=\"#\">Support</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h1>Bus Route Selection</h1>\r\n");
      out.write("        <label for=\"bus-route\">Select Bus Route:</label>\r\n");
      out.write("        <select id=\"bus-route\">\r\n");
      out.write("            <option value=\"route1\">Route 1</option>\r\n");
      out.write("            <option value=\"route2\">Route 2</option>\r\n");
      out.write("            <option value=\"route3\">Route 3</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <br><br>\r\n");
      out.write("        <a href=\"addPayment.jsp\" class=\"payment-btn\">Proceed to Payment</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"route\">\r\n");
      out.write("    <h1>Route 1: Colombo to Badulla</h1>\r\n");
      out.write("    <p>LKR:2000.00</p>\r\n");
      out.write("    <p>Colombo Fort Bus Station/ Pettah Central Bus Stand/ Maharagama Bus Station/ Ratnapura/ Balangoda/ Bandarawela/ Badulla Bus Station</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"route\">\r\n");
      out.write("    <h1>Route 2: Colombo to Jaffna</h1>\r\n");
      out.write("    <p>LKR:3000.00</p>\r\n");
      out.write("    <p>Colombo Fort Bus Station/ Maharagama Bus Stand/ Kurunegala Bus Stand/ Anuradhapura Bus Stand/ Vavuniya Bus Stand/ Jaffna Central Bus Stand</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"route\">\r\n");
      out.write("    <h1>Route 3: Colombo to Matara</h1>\r\n");
      out.write("    <p>LKR:2000.00</p>\r\n");
      out.write("    <p>Colombo Fort Bus Station/ Maharagama Bus Stand/ Panadura Bus Stand/ Kalutara Bus Stand/ Aluthgama Bus Stand/ Ambalangoda Bus Stand/ Hikkaduwa Bus Stand/ Galle Bus Stand/ Weligama Bus Stand/ Matara Central Bus Stand</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("   \r\n");
      out.write("    <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/MasterCard_Logo.svg/1200px-MasterCard_Logo.svg.png\" alt=\"Mastercard\">\r\n");
      out.write("    <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/PayPal.svg/1200px-PayPal.svg.png\" alt=\"PayPal\">\r\n");
      out.write("    <!-- Add more payment method icons as needed -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
